### ISSUE TITLE
How to assign 'scoring weight'?

### ISSUE THREAD

**Issue by y9c** [boutroslab/cld#12]
I found this line in the manual

```bash
--scoring-weights=<path/to/dir>		- the path and filename of a file defining a weight matrix with multipliers for the different scoring aspects
```

But I can't see any code for reading weight matrix.

**Comment by fheigwer** [comment]
hi yech, as I remember correctly, we removed this feature during revisions, as people seemed not to find if of great use. If you however have the impression it could be a desirable feature we could re implement it. Else we should remove it from the manual. right?

**Comment by zubairwazir** [comment]
what is the basic idea of the weight number of issues?

**Comment by zubairwazir** [comment]
can you please tell me how can we decide that this issue weight is 2 or 3 or 15 and so on??
