### ISSUE TITLE
What is naming rule of target site ID? 

### ISSUE THREAD

**Issue by y9c** [boutroslab/cld#13]
example:
`rmn1_27_1455`

What dose 27 and 1455 mean?

**Comment by fheigwer** [comment]
it is a simple convention, that is thought to just provide a unique ID for every target in that run. For the same input sequence/gene they are reproducible.

rmn1_x_y

in every run the input sequence is cut in larger pieces such that it can be distributed amongst multiple threads. The length after which a certain piece was cut [bp] is encoded in y. Starting from y we then count the x'th target site in that piece of sequence. Thus, together x and y delineate a unique ID for each and every target site.

**Comment by y9c** [comment]
Thank your fheigwer.
That is a smart solution, but I think it would be better if `cld` can sort all the targets and  make the ID meaningful.
