### ISSUE TITLE
Can't call method "seq" on an undefined value at script/cld.pl line 2641

### ISSUE THREAD

**Issue by dierckxt** [boutroslab/cld#2]
I am trying to run the current  github build of the CLD program for the target_ident task but am experiencing the error in the title in some specific genes.

Removing these genes from my gene list allows the program to proceed (until it encounters the next problem gene).

Specific problem genes I have encountered thus far:
ENSG00000143799 (PARP)
ENSG00000198793 (mTOR)
ENSG00000157404 (KIT)

Looking at the perl script, this seems to be a somewhat known issue: the offending line 
`$target  = substr $obj->seq, $start, $end - $start - 1;`
uses the "substr workaround" which was implemented because the Bioperl function doesn't work well with large numbers. It seems the workaround doesn't like large numbers that much either.

On an unrelated note:
ENSG00000108840 (HDAC5) and ENSG00000105383  (CD33) are missing from the database available for download.

**Comment by fheigwer** [comment]
Hi Tim,
This is a somewhat unexpected error. However I am sure I can fix it quite fast. A fast fix for you would be to switch the html output option to 0 (false). It should work well for you then.

**Comment by fheigwer** [comment]
Hence, I am rather sure that those genes you mentioned are in the database. They work on e-crisp.org, wich use the exact same db in the backend. I will see if I can reproduce those errors. could you PM me your parameter and gene list file?

**Comment by dierckxt** [comment]
Putting the draw_html_report parameter to 0 solved the error.

Regarding the "missing" genes, this was a problem on my end. My gene list file had trailing spaces after these two gene names, which made them unrecognizable to the program. Removing the trailing spaces fixed this.
