### ISSUE TITLE
Page not found: http://www.dkfz.de/signaling/crispr-downloads/

### ISSUE THREAD

**Issue by canfirtina** [boutroslab/cld#20]
Hello,

I would like to download the human dataset from the website you mention in the readme page. However, the page (http://www.dkfz.de/signaling/crispr-downloads/) does not exist anymore. Do you have an alternative link?

Unfortunately, using rsync is not an option for me at the moment.

Best,
Can

**Comment by canfirtina** [comment]
Closing this issue. I've found that an updated link is provided in the cld_docker GitHub page (https://github.com/boutroslab/cld_docker): http://www.e-crisp.org/E-CRISP/CLD-DB/

**Comment by canfirtina** [comment]
Reopening as the e-crisp link does not allow downloading datasets due to: `ERROR 403: Forbidden.`

**Comment by fheigwer** [comment]
Solved permission issue

**Comment by fheigwer** [comment]
thanks a thousand time for bringing this to my attention

**Comment by canfirtina** [comment]
Great, thanks for your quick response!
