### ISSUE TITLE
Feature Request: CDS exclusive PAM, unrestricted sgRNAs

### ISSUE THREAD

**Issue by dierckxt** [boutroslab/cld#3]
The parameters currently allow the selection of gene, exon and CDS exclusive sgRNAs. Would it be possible to add a setting that specifies that the PAM needs to be inside a CDS (or exon or gene, I suppose) but allows the actual sgRNA to fall outside of of this requirement?

In our current application, the fact that the sgRNA itself is intronic, or even extra-genic, is unimportant, as long as the nick is created within the CDS. However, the current options of cld only allow a restriction on the sgRNA itself, not on the PAM or the cutting site of the enzyme.

Would it be possible to add this parameter?

**Comment by fheigwer** [comment]
This was an issues that has already been discussed iteratively.

Now in version 1.2.0 I fixed the overlapping region of the sgRNA to be 3 bp proximal to the PAM ( the consensus, where the cut should occur) in version 1.2.1 this should be a tunable parameter
