### ISSUE TITLE
0.00% overall alignment rate homo_sapiens default example

### ISSUE THREAD

**Issue by ghost** [boutroslab/cld#6]
I am trying to run current CLD program for the end_to_end task for the homo_sapiens data dowloaded from the link you provid with the default params.txt and gene_list.txt (the one in cld-1.3.0-ubuntu-13.4 folder).
Some files in homo_sapiens repository are named in the wrong way (e.g. homo_sapiens.dna.2.ebwt instead of homo_sapiens.genome.2.ebwt).
Moreover, I get as the overall alignment rate 0.00% and 0 reads.

**Comment by fheigwer** [comment]
I'll have a look into that tomorrow. From your post I wonder that actually both files should be there. dna and genome.2.ebwt . Could you try the guide version and tell if that works for a small genelist. Further could you maybe zip the folder it created during the run (it should appear in you working or home directory). It is named by the time you ran the task.

Best,
Florian

**Comment by fheigwer** [comment]
I meant the version with a GUI

**Comment by fheigwer** [comment]
I looked into that issue and found the mistake in building the binary.

This should be solved now in version 1.3.1 

Please try this version and tell if we can close this issue

Florian

**Comment by ghost** [comment]
Hi Florian,

It works, thank you very much!

Best,
Lucia

2016-12-18 20:21 GMT+01:00 Florian Heigwer <notifications@github.com>:
