### ISSUE TITLE
Error  data_type=coordinates

### ISSUE THREAD

**Issue by ghost** [boutroslab/cld#7]
I am trying to run current CLD program for the end_to_end task for the homo_sapiens with the data_type parameter "coordinates". The gene list is in this form (each element in a line is tab separated): 
1      chr1	960232	960938	
2	chr1	2064895  2068273	
I get this error:
"Can't call method "next_seq" without a package or object reference at script/cld.pl line 3054"

**Comment by fheigwer** [comment]
Thank you for reporting this issue. Could you try using '1' instead of 'chr1'. As the latter is only used in non-ensembl genome builds. You can find the chromosome annotations at ensembl.org<http://ensembl.org> . I will see to fix this issue or to throw a more precise error message by tomorrow.

**Comment by ghost** [comment]
I tried with 
1	1	960232	960938	
2	1	2064895	2068273	
and I got the same error.

**Comment by fheigwer** [comment]
Hi Luctra,

It appears that CLD is doing the right thing when I tried it with corrdinates and all sorts of parameters for human or drosophila regions. I think the issue if how to input the coordinates. It is quite important that it it is a tab separated table of coordinates just like in the attached file:
[gene_list.txt](https://github.com/boutroslab/cld/files/700060/gene_list.txt)

this table needs to have the form:
id \tab chromosome \tab start \tab end \newline

simple spaces are not allowed and a unix style newline needs to be at every end on the line.
You should be able to manage this with the example I attached. If you still struggle I can have a look at your gene_list file and look whats going wrong.
